[build-system]
requires = ["setuptools>=42", "wheel", "Cython", "numpy"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = "-m \"not slow\""
markers = ["slow: marks tests as slow"]
filterwarnings = ["ignore::DeprecationWarning"]
